{
 "title": "New dashboard2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Auslastung",
   "type": "timeseries",
   "description": "Zeitreihe CPU Auslastung pro Node in %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ollama-.*\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"ollama-.*\"}) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "Anzahl Nodes in cluster",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)\r\n\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Auslastung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_cpu_seconds_total[2m])) by (instance)\r\n"
    }
   ]
  },
  {
   "title": "# Ollama Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\".*ollama.*\"}) by (node)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Auslastung pro Pod",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(rate(container_cpu_usage_seconds_total{pod=~\".*ollama.*\"}[5m])) by (pod)\r\n"
    }
   ]
  },
  {
   "title": "# Total Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info) by (node)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Speicher Auslastung ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"ollama-.*\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "RAM Auslastung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})) * 100"
    }
   ]
  },
  {
   "title": "Netzwerktraffic ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{}[2m]) + rate(container_network_transmit_bytes_total{}[2m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}