resources:
- namespace/webui.yaml
- ingress/webui-ingress.yaml
- pv/ollama-pv.yaml
# - pv/ollama2-pv.yaml
- pv/webui-pv.yaml
- pvc/ollama-pvc.yaml
# - pvc/ollama2-pvc.yaml
- pvc/webui-pvc.yaml
- deployment/ollama-deployment.yaml
# - deployment/ollama2-deployment.yaml
- deployment/webui-deployment.yaml
- service/ollama-service.yaml
# - service/ollama2-service.yaml
- service/webui-service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization