apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/SBX/cloud/Projekt/ollama/prometheus
  claimRef:
     namespace: default
     name: prometheus-pvc
