apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-webui-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: ./ollama/ollama-webui
    path: /c/SBX/cloud/Projekt/ollama/ollama-webui
  claimRef:
     namespace: default
     name: ollama-webui-pvc
